# taps
tap "nikitabobko/tap", trusted: {
    cask: "aerospace"
}
tap "felixkratz/formulae"

# formulae
brew "beads"
brew "git-delta"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "helix"
brew "python"
brew "python-lsp-server"
brew "rust-analyzer"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"
brew "xz"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "zsh-you-should-use"
brew "node"

# casks
cask "1password"
cask "aerospace"
cask "anytype"
cask "discord"
cask "hyperkey"
cask "linear"
cask "obsidian"
cask "open-island"
cask "raycast"
cask "signal"
cask "supacode"
cask "todoist-app"
cask "zed"
