# taps
tap "felixkratz/formulae"

# formulae
brew "beads"
# brew "btop"
# brew "cmatrix"
brew "git-delta"
brew "eza"
brew "fastfetch"
brew "fd"
# brew "felixkratz/formulae/sketchybar"
brew "fzf"
# brew "git-lfs"
brew "helix"
brew "hyperkey"
# brew "lazygit"
# brew "nvm"
brew "python"
brew "python-lsp-server"
brew "rust-analyzer"
brew "starship"
brew "stow"
brew "supacode"
brew "tmux"
brew "wget"
brew "xz"
# brew "yazi"
# brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "zsh-you-should-use"

# casks
cask "1password"
cask "aerospace"
cask "ghostty"
cask "obsidian"
cask "raycast"
cask "helium" # doesnt work
cask "zed"
